import dash
from dash.development.base_component import Component

import dash_html_components as html
from ertviz.plugins._webviz_ert import WebvizErtPluginABC
from ertviz.views import ensemble_selector_view
import ertviz.controllers


class EnsembleOverview(WebvizErtPluginABC):
    def __init__(self, app: dash.Dash, project_identifier: str):
        super().__init__(app, project_identifier)
        self.set_callbacks(app)

    @property
    def layout(self) -> Component:
        return html.Div(
            [
                html.P(
                    "Webvis-ERT a visualization tool for ensembles-output generated by ERT."
                ),
                html.Div(children=ensemble_selector_view(self)),
            ]
        )

    def set_callbacks(self, app: dash.Dash) -> None:
        ertviz.controllers.ensemble_selector_controller(self, app)
